apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "theia-shared-cache.fullname" . }}-node
  labels:
    app.kubernetes.io/name: {{ include "theia-shared-cache.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "theia-shared-cache.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "theia-shared-cache.fullname" . }}-node
  replicas: {{ .Values.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "theia-shared-cache.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: build-cache-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["start"]
          ports:
            - name: http
              containerPort: 5071
            - name: grpc-bazel
              containerPort: 6011
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: EXCLUSIVE_VOLUME_SIZE
              value: "{{ .Values.persistence.size }}"
          volumeMounts:
            - mountPath: /data
              name: {{ include "theia-shared-cache.fullname" . }}-data
  volumeClaimTemplates:
    - metadata:
        name: {{ include "theia-shared-cache.fullname" . }}-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"
        storageClassName: "{{ .Values.persistence.storageClass }}"
