apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: theia-shared-cache
  labels:
    app.kubernetes.io/name: theia-shared-cache
    app.kubernetes.io/instance: theia-shared-cache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: theia-shared-cache
      app.kubernetes.io/instance: theia-shared-cache
  serviceName: theia-shared-cache
  replicas: {{ .Values.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: theia-shared-cache
        app.kubernetes.io/instance: theia-shared-cache
    spec:
      containers:
        - name: theia-shared-cache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["start"]
          ports:
            - name: http
              containerPort: 5071
            - name: grpc-bazel
              containerPort: 6011
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: EXCLUSIVE_VOLUME_SIZE
              value: "{{ .Values.persistence.size }}"
          volumeMounts:
            - mountPath: /data
              name: theia-shared-cache-data-volume
  volumeClaimTemplates:
    - metadata:
        name: theia-shared-cache-data-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"
        storageClassName: "{{ .Values.persistence.storageClass }}"
