apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cache-node.fullname" . }}
  labels:
    app.kubernetes.io/part-of: gradle-enterprise
    app.kubernetes.io/component: build-cache-node
spec:
  serviceName: {{ include "cache-node.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: gradle-enterprise
      app.kubernetes.io/component: build-cache-node
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: gradle-enterprise
        app.kubernetes.io/component: build-cache-node
    spec:
      containers:
      - name: build-cache-node
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["start"]
        ports:
        - name: http
          containerPort: 5071
        - name: grpc-bazel
          containerPort: 6011
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: EXCLUSIVE_VOLUME_SIZE
          value: "{{ .Values.persistence.size }}"
        volumeMounts:
        - name: build-cache-node-data-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: build-cache-node-data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass }}
      {{- end }}
